### ISSUE TITLE
Quoting problems in args passed to logbt

### ISSUE THREAD

**Issue by springmeyer** [mapbox/logbt#28]
I noticed that if the arg passed to `logbt` for [run commands](https://github.com/mapbox/logbt#run-logbt) have spaces they may no longer be quoted correctly once sent as a subcommand:

```
./logbt -- node -e "require('./test/lib/start').before(function() { console.log('* dev server ready'); });"
```

Will error with a JS parse error because the syntax is no longer valid. I think the quotes drop out. This may be unavoidable, but ticketing in case this is fixable. It may be fixable by quoting the `@*` passed to `logbt`.

**Comment by Komzpa** [comment]
I bumped into similar issue - I need to quote spaces in Make arguments and I don't know how to:
https://github.com/postgis/postgis/pull/187/files
```
logbt -- make installcheck "RUNTESTFLAGS=--dumprestore --verbose"
```

**Comment by springmeyer** [comment]
Hi @Komzpa - I'm also not sure how to fix this. I noticed my above testcase partly breaks due to the `*` being interpreted as a special character (rather than just a normal character in a string). A simplified testcase that does not work is running `node -e "console.log('1 ');"` in `logbt`. Running it on its own works:

```
$ node -e "console.log('1 ');"
1
```

But running in logbt breaks:

```
$ ./bin/logbt -- node -e "console.log('1 ');"
[logbt] using corefile location: /cores
[logbt] using core_pattern: core.%P
[eval]:1
console.log('1
            ^^

SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:53:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:409:26)
    at node.js:648:27
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
[logbt] saw 'node' exit with code:1 (HUP)
```

**Comment by springmeyer** [comment]
@Komzpa might have a fix. Can you test https://github.com/mapbox/logbt/commit/30c554dd37b6c96c23fc424f75910fc6d6696f00?

**Comment by Komzpa** [comment]
@springmeyer patched in temporarily to https://github.com/postgis/postgis/pull/187/files, let's see if travis passes

**Comment by Komzpa** [comment]
@springmeyer it's not finished yet but not all-red already, so it helped!

**Comment by springmeyer** [comment]
great to hear @Komzpa. I'm seeing one failure in the unit tests (https://travis-ci.org/mapbox/logbt/builds/327411636?utm_source=github_status&utm_medium=notification) that I don't understand, so I won't merge yet.

**Comment by springmeyer** [comment]
Figured out what is happening. Due to the way that docker works, this command is being sent to logbt:

```
./bin/logbt -- 'node test/wait.js 1'
```

Which fails with this branch:

```
[logbt] using corefile location: /tmp/logbt-coredumps
[logbt] using core_pattern: core.%p.%E
./bin/logbt: line 251: node test/wait.js 5: No such file or directory
./bin/logbt: line 270: wait: `/tmp/logbt-coredumps': not a pid or valid job spec
[logbt] saw 'node' exit with code:1 (HUP)
```

While this works:

```
./bin/logbt -- node test/wait.js 1
[logbt] using corefile location: /tmp/logbt-coredumps
[logbt] using core_pattern: core.%p.%E
Process id is 148
Running for 1 s
Running tic # 0
Running tic # 1
Running tic # 2
Running tic # 3
Done after 4 tics, forcing exit
Exiting with 0
```

**Comment by springmeyer** [comment]
Just realized the above comment should have been at the PR for this at #33. Anyway, its fixed now.
