### ISSUE TITLE
Add ability to keep core dump

### ISSUE THREAD

**Issue by springmeyer** [mapbox/logbt#31]
The default behavior of `logbt` is to:

   - Notice coredump(s) on the system
   - Generate backtraces for each and print them to stdout
   - Remove the coredump(s) to avoid the potential of the disk filling up when multiple processes crash(ed)

However, for deeper debugging `logbt` could accept an option to keep the core dump.

## --keep-core

If passed this option would disable the auto-removal of coredumps [here](https://github.com/mapbox/logbt/blob/fb3c289bdd9e19c45b259101e873638059f4e8b2/bin/logbt#L42).

This would allow developers to ssh into a machine and manually investigate the coredump.

It would also allow for a system to be built - outside of logbt - to potentially upload the coredump for later retrieval.

The by-product of keeping the coredump around would be that if another process started on the same machine (or docker container) it would also notice the existing coredump, [print a warning](https://github.com/mapbox/logbt/blob/fb3c289bdd9e19c45b259101e873638059f4e8b2/bin/logbt#L246), and then generate a second backtrace for the existing coredump when that process exited.

**Comment by oxidase** [comment]
@springmeyer :+1: that would be nice to have. One thing to mention: core dumps do not contain `text` sections, so to use dumps with gdb all binary files with corresponding checksum will be needed.

**Comment by springmeyer** [comment]
@oxidase okay - do you have any suggestions for ways `logbt` could or should make that easier? Should the binary (which `logbt` knows about on linux because it is embedded in the coredump path) be archived as well?

**Comment by daniel-j-h** [comment]
Yes archiving the binary would be great. Maybe we should fingerprint the binaries (passing [`--build-id`](https://sourceware.org/binutils/docs-2.23.1/ld/Options.html#Options) to the linker) in our projects, too. In case of shared libraries we also need them to be archived (think: `libtbb.so` in the context of osrm) along the binary.

Also in the context of osrm the question is how to handle shared memory in core dumps. The Linux Kernel v2.6.23+ has an option (search for `coredump_fitler` [here](http://man7.org/linux/man-pages/man5/core.5.html)) which we could explore for this use-case.

**Comment by oxidase** [comment]
@daniel-j-h @springmeyer I think the best would to "freeze" an instance if an segfault/abort occurred and remove the instance after manual check, but i don't know if it is easy or acceptable solution.

List of binaries (it can be incomplete but at least required):
* executable from the string  `Core was generated by /usr/bin/executable.`
* the last column of `info sharedlibrary` output
```
From                To                  Syms Read   Shared Object Library
0x00007ffff7dd7aa0  0x00007ffff7df5370  Yes         /lib64/ld-linux-x86-64.so.2
0x00007ffff7b81fd0  0x00007ffff7bc4700  Yes (*)     /home/miha/foss/boost/stage/lib/libboost_program_options.so.1.64.0
```

**Comment by oxidase** [comment]
just looked into man pages http://man7.org/linux/man-pages/man5/core.5.html : probably it is enough just  to set additionally bits 3 and/or 2 of `coredump_filter` to have proper coredmps. But i would try first and check how coredump file size will increase.

**Comment by springmeyer** [comment]
Done in f4abe4a6d184f28c0da2789ff59a348d82ae29c0. As far as bundling up all binaries that might be involved in a crash: that is out of scope for logbt and would need to be accomplished by some other tooling.
