### ISSUE TITLE
Add ability to upload core file to s3

### ISSUE THREAD

**Issue by corporategoth** [mapbox/logbt#47]
If this is used in an ephemeral container, once the container is cleaned up the core files are gone (even with --keep-cores).

We should have the option to upload to an S3 bucket core files (marked in some way that is identifiable).

The S3 bucket could be set to expire files after 90 days or something automatically, but that's beyond the scope of this ticket.

**Comment by springmeyer** [comment]
I think the uploading should be handled outside of logbt, since each different user might have different authentication needs.

**Comment by jaericson** [comment]
Based on https://github.com/mapbox/api-maps/issues/1753 today, @corporategoth proposed also merging this change into `api-maps`.
